<template>
  <div class="modal fade" id="importdeckmodal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Import Deck</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <span id="base-link">https://pastebin.com/</span>
          <input v-model="key" type="text" required>
          <br><br>
          <span id="instruction">Please input valid Flashero pastebin key. A valid pastebin file would be the one that was generated by using flashero export feature or <a href="https://pastebin.com/af33tAAF" target="_blank">have a format like this</a></span>
        </div>
        <div class="modal-footer">
          <span id="info">This will create a new deck with the name and cards from the link</span>
          <button @click="importDeck()" type="button" class="btn btn-outline-success" data-bs-dismiss="modal">Submit</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'DeckForm',

  data () {
    return {
      key: ''
    }
  },

  methods: {
    importDeck () {
      this.$store.dispatch('importDeck', { key: this.key })
      this.key = ''
    }
  }
}
</script>

<style scoped>
  #base-link {
    font-weight:bold;
    font-size: 1.2em;
  }

  #instruction {
    font-size: 1em;
    color: forestgreen
  }

  #info {
    color:orangered
  }

  h5 {
    font-weight: bold;
  }
</style>
